config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'books#index'
  resources :books
  resources :patrons
  resources :checkouts do
    member do
      post 'return'
      post 'complete_return'
    end
  end

  resources :returns, only: [] do
    member do
      get 'return'
      patch 'complete_return'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
    has_many :checkouts
    scope :search, ->(query) 
    {
        where('title LIKE ? OR author LIKE ? OR isbn LIKE ?', "%#{query}%", "%#{query}%", "%#{query}%")
    }
end
  

app/models/checkout.rb
class Checkout < ApplicationRecord
  belongs_to :book
  belongs_to :patron

  validates :checked_out_at, presence: true
  validates :due_date, presence: true

  validate :due_date_after_checked_out_at

  def due_date_after_checked_out_at
    return unless checked_out_at.present? && due_date.present?

    errors.add(:due_date, 'must be after the check-out date') if due_date <= checked_out_at
  end
end

app/models/patron.rb
class Patron < ApplicationRecord
    has_many :checkouts
    attr_accessor :email
end
  

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  
  enum user_type: [:regular_user, :patron]
  def admin?
    user_type == 'admin'
  end

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    before_action :authorize_admin
  protected
  
  def authorize_admin
    unless current_user.admin?
      redirect_to root_path, alert: 'You are not authorized to perform this action.'
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:user_type])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!

  def index
    @books = Book.all
    @books = @books.search(params[:query]) if params[:query].present?
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to books_path, notice: 'Book added successfully.'
    else
      render :new
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to books_path, notice: 'Book updated successfully.'
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path, notice: 'Book removed successfully.'
  end

  private

  def book_params
    params.require(:book).permit(:title, :author, :isbn, :available)
  end

  def authorize_user
    redirect_to root_path, alert: 'You are not authorized to perform this action' unless current_user && current_user.regular_user?
  end
  
end

app/controllers/checkouts_controller.rb
class CheckoutsController < ApplicationController
  before_action :authenticate_user!
  before_action :authorize_user, except: [:index, :show]

  def index
    @checkouts = Checkout.all
  end

  def show
    @checkout = Checkout.find(params[:id])
  end

  def new
    @checkout = Checkout.new
  end

  def create
    @checkout = Checkout.new(checkout_params)
    if @checkout.save
      redirect_to checkouts_path, notice: 'Checkout added successfully.'
    else
      render :new
    end
  end

  def edit
    @checkout = Checkout.find(params[:id])
  end

  def update
    @checkout = Checkout.find(params[:id])
    if @checkout.update(checkout_params)
      redirect_to checkouts_path, notice: 'Checkout updated successfully.'
    else
      render :edit
    end
  end

  def destroy
    @checkout = Checkout.find(params[:id])
    @checkout.destroy
    redirect_to checkouts_path, notice: 'Checkout deleted successfully.'
  end

  def returns
    @checkout = Checkout.find(params[:id])
    # Add logic for returning a checkout if needed
    redirect_to returns_return_path(@checkout)
  end

  private

  def checkout_params
    params.require(:checkout).permit(:book_id, :patron_id, :checked_out_at, :due_date, :returned_at)
  end

  def authorize_user
    redirect_to root_path, alert: 'You are not authorized to perform this action' unless current_user && current_user.regular_user?
  end
end

app/controllers/patrons_controller.rb
class PatronsController < ApplicationController
  before_action :authenticate_user!

  def index
    @patrons = Patron.all
  end

  def show
    @patron = Patron.find(params[:id])
  end

  def new
    @patron = Patron.new
  end

  def create
    @patron = Patron.new(patron_params)
    
    respond_to do |format|
      if @patron.save
        format.html { redirect_to @patron, notice: 'Patron was successfully created.' }
        format.json { render :show, status: :created, location: @patron }
      else
        format.html { render :new }
        format.json { render json: @patron.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @patron = Patron.find(params[:id])
  end
  
  def update
    @patron = Patron.find(params[:id])
    if @patron.update(patron_params)
      redirect_to patrons_path, notice: 'Patron updated successfully.'
    else
      render :edit
    end
  end

  def destroy
    @patron = Patron.find(params[:id])
    @patron.destroy
    redirect_to patrons_path, notice: 'Patron removed successfully.'
  end
  

  private
  def patron_params
    params.require(:patron).permit(:name, :id_number, :email, :password, :password_confirmation)
  end
  
  def authorize_user
    unless current_user.admin? || @patron == current_user
      redirect_to root_path, alert: 'You are not authorized to perform this action.'
    end
  end

  def authorize_patron
    redirect_to root_path, alert: 'You are not authorized to perform this action' unless current_user && current_user.patron?
  end
end

app/controllers/returns_controller.rb
class ReturnsController < ApplicationController
  before_action :find_checkout, only: [:return, :complete_return]

  def return
  end

  def complete_return
    @checkout.returned_at = DateTime.current
  
    if @checkout.save
      redirect_to checkouts_path, notice: 'Book returned successfully.'
    else
      render :return
    end
  end

  private

  def find_checkout
    @checkout = Checkout.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/checkouts_helper.rb
module CheckoutsHelper
end

app/helpers/patrons_helper.rb
module PatronsHelper
end

app/helpers/returns_helper.rb
module ReturnsHelper
end

app/views/books/_form.html.erb
<%= form_with(model: book || Book.new, local: true) do |form| %>
  <% if book&.errors&.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :title, class: "form-label" %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :author, class: "form-label" %>
    <%= form.text_field :author, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :isbn, class: "form-label" %>
    <%= form.text_field :isbn, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :available, class: "form-check-label" %>
    <%= form.check_box :available, class: "form-check-input" %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/books/edit.html.erb
<div class="container mt-4">
  <h1>Edit Book</h1>

  <%= render 'form', book: @book %>

  <%= link_to 'Back to Books', books_path, class: 'btn btn-secondary mt-3' %>
</div>

app/views/books/index.html.erb
<%= render 'shared/navbar' %>

<div class="container mt-4">
  <div class="jumbotron">
    <h1 class="display-4">Library Books</h1>
    <%= link_to 'Add New Book', new_book_path, class: 'btn btn-primary btn-lg' %>
  </div>

  <div class="row mb-4">
    <div class="col-md-8 offset-md-2">
      <%= form_tag(books_path, method: :get, class: "form-inline", id: "search-form") do %>
        <div class="input-group">
          <%= text_field_tag(:query, params[:query], class: "form-control", placeholder: "Search by title, author, or ISBN") %>
          <div class="input-group-append">
            <%= button_tag(type: 'submit', class: 'btn btn-primary') do %>
              <i class="fa fa-search"></i> Search
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>

  <table class="table">
    <thead>
      <tr>
        <th>Title</th>
        <th>Author</th>
        <th>ISBN</th>
        <th>Available</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <% if @books.present? %>
        <% @books.each do |book| %>
          <tr>
            <td><%= book.title %></td>
            <td><%= book.author %></td>
            <td><%= book.isbn %></td>
            <td><%= book.available ? 'Yes' : 'No' %></td>
            <td>
              <%= link_to 'Show', book %>
              <%= link_to 'Edit', edit_book_path(book) %>
              <%= link_to 'Delete', book, method: :delete, data: { confirm: 'Are you sure?' }, class: 'text-danger' %>
            </td>
          </tr>
        <% end %>
      <% else %>
        <tr>
          <td colspan="5"><%= flash[:notice] %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<script>
  document.addEventListener('DOMContentLoaded', function () {
    const searchForm = document.getElementById('search-form');
    if (searchForm) {
      searchForm.addEventListener('submit', function () {
        setTimeout(function () {
          searchForm.reset();
        }, 0);
      });
    }
  });
</script>

app/views/books/new.html.erb
<%= render 'shared/navbar' %>

<div class="container mt-4">
  <h1>New Book</h1>

  <%= render 'form', book: @book %>

  <%= link_to 'Back', books_path, class: 'btn btn-secondary mt-3' %>
</div>

app/views/books/show.html.erb
<div class="container mt-4">
  <div class="card">
    <div class="card-body">
      <h1 class="card-title"><%= @book.title %></h1>
      <p class="card-text">Author: <%= @book.author %></p>
      <p class="card-text">ISBN: <%= @book.isbn %></p>
      <p class="card-text">Available: <%= @book.available ? 'Yes' : 'No' %></p>

      <%= link_to 'Back to Books', books_path, class: 'btn btn-primary' %>
    </div>
  </div>
</div>

app/views/checkouts/_form.html.erb
<%= form_with(model: checkout, local: true) do |form| %>
  <% if checkout.errors.any? %>
    <div class="alert alert-danger">
      <ul>
        <% checkout.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :book_id %>
    <%= form.collection_select :book_id, Book.all, :id, :title, { prompt: 'Select Book' }, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :patron_id %>
    <%= form.collection_select :patron_id, Patron.all, :id, :name, { prompt: 'Select Patron' }, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :checked_out_at %>
    <%= form.datetime_select :checked_out_at, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :due_date %>
    <%= form.datetime_select :due_date, class: 'form-control' %>
  </div>

  <%= form.submit 'Save', class: 'btn btn-primary' %>
<% end %>

app/views/checkouts/edit.html.erb
<h1>Edit Checkout</h1>
<%= render 'form', checkout: @checkout %>
<%= link_to 'Back', checkouts_path %>

app/views/checkouts/index.html.erb
<%= render 'shared/navbar' %>

<div class="container mt-4">
  <div class="jumbotron">
    <h1 class="display-4">Library Checkouts</h1>
    <%= link_to 'Add New Checkout', new_checkout_path, class: 'btn btn-primary btn-lg' %>
  </div>

  <table class="table">
    <thead>
      <tr>
        <th>Book</th>
        <th>Patron</th>
        <th>Checked Out At</th>
        <th>Due Date</th>
        <th>Returned At</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <% @checkouts.each do |checkout| %>
        <tr>
          <td><%= checkout.book.title %></td>
          <td><%= checkout.patron.name %></td>
          <td><%= checkout.checked_out_at %></td>
          <td><%= checkout.due_date %></td>
          <td><%= checkout.returned_at.presence || "-" %></td>
          <td>
            <%= link_to 'Show', checkout %>
            <%= link_to 'Edit', edit_checkout_path(checkout) %>
            <%= link_to 'Delete', checkout, method: :delete, data: { confirm: 'Are you sure?' }, class: 'text-danger' %>
            <% unless checkout.returned_at.present? %>
              <%= button_to 'Return Book', return_checkout_path(checkout), method: :post, class: 'btn btn-danger', data: { confirm: 'Are you sure?' } %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/checkouts/new.html.erb
<%= render 'shared/navbar' %>

<div class="container mt-4">
  <h1>New Checkout</h1>
  <%= render 'form', checkout: @checkout %>
  <%= link_to 'Back', checkouts_path %>
</div>

app/views/checkouts/show.html.erb
<%= render 'shared/navbar' %>

<div class="container mt-4">
  <div>
    <h1>Checkout Details</h1>
    
    <p>Book: <%= @checkout.book.title %></p>
    <p>Patron: <%= @checkout.patron.name %></p>
    <%= link_to 'Back to Checkouts', checkouts_path, class: 'btn btn-primary' %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LibraryManagementSystem</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'https://code.jquery.com/jquery-3.6.0.min.js' %>
    <%= javascript_include_tag 'application.js', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/js/all.min.js"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/patrons/_form.html.erb
<%= form_with(model: patron, local: true) do |form| %>
  <% if patron.errors.any? %>
    <div class="alert alert-danger">
      <ul>
        <% patron.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :id_number %>
    <%= form.text_field :id_number, class: 'form-control' %>
  </div>

  <%= form.submit 'Save', class: 'btn btn-primary' %>
<% end %>

app/views/patrons/edit.html.erb
<div class="container mt-4">
  <h1>Edit Patron</h1>

  <%= render 'form', patron: @patron %>

  <%= link_to 'Back to Patrons', patrons_path, class: 'btn btn-secondary' %>
</div>

app/views/patrons/index.html.erb
<%= render 'shared/navbar' %>

<div class="container mt-4">
  <div class="jumbotron">
    <h1 class="display-4">Patrons</h1>
    <%= link_to 'Add New Patron', new_patron_path, class: 'btn btn-primary btn-lg' %>
  </div>

  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>ID Number</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <% @patrons.each do |patron| %>
        <tr>
          <td><%= patron.name %></td>
          <td><%= patron.id_number %></td>
          <td>
            <%= link_to 'Show', patron %>
            <%= link_to 'Edit', edit_patron_path(patron) %>
            <%= link_to 'Destroy', patron, method: :delete, data: { confirm: 'Are you sure?' }, class: 'text-danger' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/patrons/new.html.erb
<%= render 'shared/navbar' %>

<div class="container mt-4">
  <h1>New Patron</h1>

  <%= render 'form', patron: @patron %>

  <%= link_to 'Back', patrons_path, class: 'btn btn-secondary mt-3' %>
</div>

app/views/patrons/show.html.erb
<div class="container mt-4">
  <div class="card">
    <div class="card-body">
      <h1 class="card-title"><%= @patron.name %></h1>
      <p class="card-text">ID Number: <%= @patron.id_number %></p>
      <%= link_to 'Back to Patrons', patrons_path, class: 'btn btn-primary' %>
    </div>
  </div>
</div>

app/views/returns/return.html.erb
<h1>Return Book</h1>
<p>Are you sure you want to return this book?</p>

<%= link_to 'Cancel', checkouts_path, class: 'btn btn-secondary' %>

<%= form_with(model: @checkout, url: complete_return_checkout_path(@checkout), method: :post) do |form| %>
  <div class="mb-3">
    <%= form.label :returned_at %>
    <%= form.datetime_select :returned_at, class: 'form-control' %>
  </div>

  <%= form.submit 'Return', class: 'btn btn-danger' %>
<% end %>

app/views/shared/_navbar.html.erb
<!-- app/views/shared/_navbar.html.erb -->

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <%= link_to 'Library Management System', root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Books', books_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Patrons', patrons_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Checkouts', checkouts_path, class: 'nav-link' %>
          </li>
        <% end %>

        <% if user_signed_in? %>
          <li class="nav-item">
            <%= button_to 'Logout', destroy_user_session_path, method: :delete, class: 'nav-link' %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Login', new_user_session_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Signup', new_user_registration_path, class: 'nav-link' %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>